name: bench

on:
  pull_request:
    branches: ['**']

jobs:
  bench:
    name: perf
    runs-on: ubuntu-latest

    steps:
      # Check out master an pr branches
      - uses: actions/checkout@v4
        with:
          path: pr
      - uses: actions/checkout@v4
        with:
          ref: master
          path: master
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      # Prepare master sources
      - name: bench master (baseline)
        run: |
          cd master && npm install && npm run build && \
          sed -i 's|"./h"|"./h.js"|g' ./build/jsx.js
      # Prepare pr sources. Run benchmarks and output to a separate files
      - name: bench pr
        run: |
          cd pr && npm install && npm run build && \
          sed -i 's|"./h"|"./h.js"|g' ./build/jsx.js && \
          npm run bench:setup && \
          npm run bench | tee benchmarks.pr.txt && \
          sed -i 's|"file:../../"|"file:../../../master/"|g' ./test/bench/package.json && \
          npm run bench | tee benchmarks.master.txt && \
          echo "---------------" && \
          echo "benchmarks results;" && \
          echo "tail -1 benchmarks.pr.txt" && \
          tail -1 benchmarks.pr.txt && \
          echo "tail -1 benchmarks.master.txt" && \
          tail -1 benchmarks.master.txt
        
      - name: bench compare master to pr
        uses: openpgpjs/github-action-pull-request-benchmark@v1
        with:
          name: "Time benchmark"
          # What benchmark tool the benchmarks.txt files came from
          tool: "benchmarkjs"
          # Where the two output files from the benchmark tool are stored
          pr-benchmark-file-path: pr/benchmarks.pr.txt
          base-benchmark-file-path: pr/benchmarks.master.txt
          # A comment will be left on the latest PR commit if `alert-threshold` is exceeded
          comment-on-alert: true
          alert-threshold: "130%"
          # Workflow will fail if `fail-threshold` is exceeded
          fail-on-alert: true
          fail-threshold: "150%"
          # A token is needed to leave commit comments
          github-token: ${{ secrets.GITHUB_TOKEN }}
